package game;

import java.util.Arrays;
import java.util.Objects;
import java.util.Scanner;

/**
 * Main game controller for the Snake game.
 * <p>
 * Handles game initialization, main loop, input processing, and rendering.
 * Delegates movement, collision detection, and board updates to Snake and Board.
 * </p>
 * javadoc generated by chatgpt. April 25th 2025
 */
public class SnakeGame {

    private Snake snake;
    private Apple apple;
    private Board board;
    private int boardRows;
    private int boardColumns;
    private GameState state;

    // to test program
    public static void main(String[] args) throws InterruptedException {
        SnakeGame game = new SnakeGame();

    }

    public SnakeGame() throws InterruptedException {
        startGame();

    }

    /**
     * Initializes game components and runs the main game loop until over.
     *
     * @throws InterruptedException if thread sleep is interrupted
     */
    public void startGame() throws InterruptedException {

        boardColumns = 20;
        boardRows = 20;
        board = new Board(boardColumns, boardRows);

        snake = new Snake(boardColumns/2, boardRows/2); //spawn snake in middle of board

        apple = new Apple();
        apple.setBoard(board);

        state = GameState.RUNNING;

        while(state == GameState.RUNNING) {
            gameLoop(snake, apple);

        }
    }

    /**
     * Runs one interation of the main game loop:
     * spawns apple, reads input, moves the snake,
     * checks for collisions, handles eating, updates board,
     * and prints the new state.
     */
    public void gameLoop(Snake snake, Apple apple){

        apple.spawn();

        // Change direction using text
        Scanner scanner = new Scanner(System.in);
        String direction = scanner.nextLine();
        if (Objects.equals(direction, "w")) {
            snake.changeDirection(Direction.NORTH);
        } else if (Objects.equals(direction, "a")) {
            snake.changeDirection(Direction.WEST);
        } else if (Objects.equals(direction, "s")) {
            snake.changeDirection(Direction.SOUTH);
        } else if (Objects.equals(direction, "d")) {
            snake.changeDirection(Direction.EAST);
        }
        // ================

        snake.move();

        // if snake is died
        if (snake.hasCrashed(boardColumns, boardRows)){
            state = GameState.GAME_OVER;
            System.out.println("game over you suck");
            return; // makes program stop drawing the grid after a crash. gets rid of annoying out-of-bounds error message
        }

        // if snake eats apple
        if (Arrays.toString(snake.getHead()).equals(Arrays.toString(apple.getApplePosition()))){
            snake.eat();
            apple.despawn();
            apple.spawn();
        }

        board.updateBoard(snake, apple);

        // print the board. update board upon pressing enter
        for (int[] element : board.getGrid()) {
            System.out.println(Arrays.toString(element));
        }
        System.out.println("===============================================");
        // ===============

    }
}