package game;

import org.controlsfx.control.tableview2.filter.filtereditor.SouthFilter;

import java.util.Arrays;
import java.util.LinkedList;

/**
 * Represents the snake in the Snake game.
 * <p>
 * Manages the snake's body segments, movement direction, growth when eating,
 * and collision detection against walls and itself.
 * </p>
 * javadoc generated by chatgpt. April 25th 2025
 */
public class Snake {

    private LinkedList<int[]> body;
    private int[] lastRemovedTail;
    private int size;
    private Direction currentDirection;
    private boolean shouldGrow;

    /**
     * Constructs a new snake at the given starting position, starting at length 1,
     * moving east by default.
     *
     * @param startX the starting column index for the snake's head
     * @param startY the starting row index for the snake's head
     */
    public Snake(int startX, int startY){
        body = new LinkedList<>();
        body.add(new int[]{startX, startY});

        currentDirection = Direction.EAST;
        shouldGrow = false;

        this.size = 1;
    }

    /**
     * Moves the snake one cell in the current direction.
     * <p>
     * Adds a new head segment, and if not growing, removes the tail segment,
     * caching it for board clearing. If growing, increases size and resets grow flag.
     * </p>
     * javadoc generated by chatgpt. April 25th 2025
     */
    public void move(){

        int[] head = getHead();
        int x = head[0];
        int y = head[1];

        if (currentDirection == Direction.NORTH){
            y--;
        } else if (currentDirection == Direction.WEST) {
            x--;
        } else if (currentDirection == Direction.SOUTH) {
            y++;
        } else { //if (currentDirection == Direction.EAST)
            x++;
        }

        body.addFirst(new int[]{x,y});

        if (!shouldGrow) {
            lastRemovedTail = body.removeLast();

        } else { // if (shouldGrow)
            lastRemovedTail = null;
            shouldGrow = false;
            size++;
        }
    }

    /**
     * Snake grows 1 length on its next move.
     */
    public void eat(){
        shouldGrow = true;
    }

    /**
     * Changes the snake's direction, rejecting reversals (180° turns).
     *
     * @param newDirection the new direction of movement
     */
    public void changeDirection(Direction newDirection){
        if ((currentDirection == Direction.NORTH && newDirection == Direction.SOUTH) ||
                (currentDirection == Direction.SOUTH && newDirection == Direction.NORTH) ||
                (currentDirection == Direction.WEST  && newDirection == Direction.EAST) ||
                (currentDirection == Direction.EAST  && newDirection == Direction.WEST)) {

            //error message: snake cant reverse direction
            System.err.println("snake cant reverse direction");

        } else {
            this.currentDirection = newDirection;
        }
    }

    /**
     * Checks whether the snake has hit a wall or itself.
     *
     * @param boardColumns the width of the board (max x)
     * @param boardRows    the height of the board (max y)
     * @return true if head is out of bounds or overlaps body, false otherwise.
     */
    public boolean hasCrashed(int boardColumns, int boardRows){

        int[] head = getHead();
        int x = head[0];
        int y = head[1];

        // crashes into wall
        if (x < 0 || y < 0 || x >= boardColumns || y >= boardRows){
            return true;
        }

        // crashes into itself
        for (int i = 1; i < body.size(); i++){
            if (Arrays.equals(head, body.get(i))){
                return true;
            }
        }

        // doesnt crash
        return false;
    }

    /**
     * Returns the list of all body segment coordinates, head first.
     *
     * @return a LinkedList of {x,y} pairs for each segment
     * javadoc generated by chatgpt. April 25th 2025
     */    public LinkedList<int[]> getBody(){
        return body;
    }

    /**
     * Returns the current head position of the snake.
     *
     * @return an {x,y} array for the head segment
     * javadoc generated by chatgpt. April 25th 2025
     */
    public int[] getHead(){
        // i wish this had the other interpretation but this is fine too
        return body.get(0);
    }

    /**
     * Indicates whether the snake is flagged to grow on next move.
     *
     * @return true if growth is pending, false otherwise
     * javadoc generated by chatgpt. April 25th 2025
     */
    public boolean getShouldGrow(){
        return shouldGrow;
    }
    
    /**
     * Returns the most recently removed tail segment
     *
     * @return an {x,y} array of the removed tail, or null if the snake just grew
     */
    public int[] getLastRemovedTail() {
        return lastRemovedTail;
    }

}
