package controllers;

import game.TopScore;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.Objects;
import java.util.ResourceBundle;

/**
 * Controller for the main-menu scene of the SnakeFX application.
 *
 * <p>This class is responsible for:</p>
 * <ul>
 *   <li>Displaying the current <strong>top score</strong>.</li>
 *   <li>Playing looping background <strong>menu music</strong>.</li>
 *   <li>Handling the <em>Play</em> button to switch to the game scene.</li>
 * </ul>
 *
 * javadoc generated by chatgpt. April 27 2025
 */
public class MenuController implements Initializable {

    private MediaPlayer menuMusic;

    @FXML
    private Button playButton;
    @FXML
    private Label topScoreDisplay;

    /**
     * <p>Initialises UI elements and resources:</p>
     * <ol>
     *   <li>Loads <code>/menu_soundtrack.mp3</code>, creates a looping
     *       {@link MediaPlayer}, and starts playback.</li>
     * </ol>
     *
     * @param url            the location used to resolve relative paths for the FXML (unused)
     * @param resourceBundle the resources used for localisation (unused)
     *
     * javadoc generated by chatgpt. April 27 2025
     */
    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        // generate top score
        topScoreDisplay.setText("TOP SCORE: " + TopScore.getScoreFromFile());

        // play music
        try {
            URL resource = getClass().getResource("/menu_soundtrack.mp3");
            if (resource != null) {
                Media media = new Media(resource.toExternalForm());
                menuMusic = new MediaPlayer(media);
                menuMusic.setCycleCount(MediaPlayer.INDEFINITE);
                menuMusic.setVolume(0.2);
                menuMusic.play();
            } else {
                System.out.println("Menu music file not found!");
            }
        } catch (Exception e) {
            System.out.println("Error loading menu music.");
            e.printStackTrace();
        }
    }

    /**
     * Event-handler invoked when the user presses the <em>Play</em> button.
     *
     * <p>This method stops the background music and swaps the current scene
     * to <code>board.fxml</code>, which contains the game board.</p>
     *
     * @param event the button click event supplied by JavaFX
     * @throws IOException if the FXML for the game board cannot be loaded
     *
     * javadoc generated by chatgpt. April 27 2025
     */
    public void play(ActionEvent event) throws IOException {
        menuMusic.stop();

        Parent newRoot = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("board.fxml")));

        Stage stage = (Stage) playButton.getScene().getWindow();

        stage.setScene(new Scene(newRoot));
        stage.setTitle("Snake");
        stage.show();
    }



}
